# Generated by Django 3.2.4 on 2021-06-08 19:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SelvaPampa', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='usuario',
            name='email',
            field=models.CharField(default=None, max_length=50),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='usuario',
            name='password',
            field=models.CharField(max_length=50),
        ),
    ]
