# Generated by Django 3.2.4 on 2021-06-13 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('SelvaPampa', '0004_auto_20210613_1714'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='sustrato',
            new_name='substratum',
        ),
    ]
